import { describe, expect, it } from 'vitest';
import { CANALES_IPC, type CanalIpc } from './contrato';

/**
 * Todos los canales del contrato. Si se agrega un canal a `ContratoIpc` y
 * no aquí, TypeScript marca error; si no se agrega a `CANALES_IPC`, falla la prueba.
 */
const TODOS_LOS_CANALES = {
  'autenticacion:estado': true,
  'autenticacion:crear': true,
  'autenticacion:ingresar': true,
  'autenticacion:cambiar': true,
  'autenticacion:restablecer': true,
  'autenticacion:generarClave': true,
  'sistema:info': true,
  'sistema:registrarError': true,
  'sistema:copiarTexto': true,
  'app:confirmarCierre': true,
  'negocio:obtener': true,
  'negocio:guardar': true,
  'productos:listar': true,
  'productos:obtener': true,
  'productos:siguienteCodigo': true,
  'productos:crear': true,
  'productos:editar': true,
  'productos:cambiarEstado': true,
  'productos:corregirCosto': true,
  'terceros:listar': true,
  'terceros:siguienteCodigo': true,
  'terceros:crear': true,
  'terceros:editar': true,
  'terceros:cambiarEstado': true,
  'catalogos:listar': true,
  'catalogos:crear': true,
  'catalogos:editar': true,
  'catalogos:cambiarEstado': true,
  'importador:validar': true,
  'importador:importar': true,
  'importador:guardarReporte': true,
  'compras:contexto': true,
  'compras:contextoProveedor': true,
  'compras:stockBodega': true,
  'compras:guardar': true,
  'abonos:contexto': true,
  'abonos:contextoTercero': true,
  'abonos:guardar': true,
  'abonos:anular': true,
  'ajustes:listar': true,
  'ajustes:stock': true,
  'ajustes:registrar': true,
  'ajustes:anular': true,
  'correcciones:buscarVenta': true,
  'correcciones:buscarCompra': true,
  'correcciones:corregirVenta': true,
  'correcciones:corregirCompra': true,
  'correcciones:anular': true,
  'devoluciones:contexto': true,
  'devoluciones:guardar': true,
  'devoluciones:anular': true,
  'saldoFavor:consultar': true,
  'saldoFavor:reintegrar': true,
  'saldoFavor:anularReintegro': true,
  'ventas:contexto': true,
  'ventas:creditoCliente': true,
  'ventas:guardar': true,
  'ventas:borradores': true,
  'ventas:guardarBorrador': true,
  'ventas:borrarBorrador': true,
  'facturacion:configuracion': true,
  'facturacion:configurar': true,
  'facturacion:impresoras': true,
  'impresion:html': true,
  'impresion:imprimir': true,
  'impresion:pdf': true,
  'reimpresiones:buscar': true,
  'reportes:inventario': true,
  'reportes:cartera': true,
  'reportes:html': true,
  'reportes:imprimir': true,
  'reportes:pdf': true,
  'reportes:excel': true,
  'interfaz:preferencias': true,
  'interfaz:guardarBarra': true,
  'interfaz:guardarVentana': true,
  'interfaz:restablecerVentanas': true,
} as const satisfies Record<CanalIpc, true>;

describe('lista blanca de canales IPC', () => {
  it('coincide exactamente con el contrato', () => {
    expect([...CANALES_IPC].sort()).toEqual(Object.keys(TODOS_LOS_CANALES).sort());
  });
});
